In [6]:
import numpy as np

In [12]:
arr=np.array([[[1,2],[6,5]],[[7,8],[9,10]]])

In [13]:
arr.ndim

3

In [15]:
print(arr)

[[[ 1  2]
  [ 6  5]]

 [[ 7  8]
  [ 9 10]]]


In [14]:
np.sort(arr)

array([[[ 1,  2],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10]]])

In [17]:
arr1=np.where(arr>5,0,1)

In [18]:
print(arr1)

[[[1 1]
  [0 1]]

 [[0 0]
  [0 0]]]
